### ISSUE TITLE
Failed to Retrieve Temperature from Prusa MINI: HAP Status Error (-70403)

### ISSUE THREAD

**Issue by Flavien06** [apexskier/homebridge-prusalink#1]
Hello, I have this error :

**Logs:**

```
[ApexskierHomebridgePrusaLink] error getting temperature HapStatusError: HAP Status Error: -70403
    at new HapStatusError (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/hapStatusError.ts:17:10)
    at CurrentTemperature.getHandler (/var/lib/homebridge/node_modules/@apexskier/homebridge-prusalink/src/platformAccessory.ts:111:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  hapStatus: -70403
}
```

**Environment:**

* **Plugin Version**: 1.0.6
* **Homebridge Version**:  1.8.4
* **Node.js Version**:  v20.17.0
* **NPM Version**:  10.8.2
* **Operating System**:  Raspberry Pi 3 Model B Rev 1.2 "Raspbian 11" / Kernel: Linux 6.1.65-v7+

**Comment by apexskier** [comment]
This most likely came from https://github.com/apexskier/homebridge-prusalink/blob/b01677203e858a511dcb4144778b716ccc310b28/src/platformAccessory.ts#L112, which happens when the printer is attempting to reach a specific temp (preheating or actively printing) or in my simple heuristic for "cooling down" (temps are way different than each other). That's all expected.
